# DATA
COLUMN_YEAR = "YEAR"
COLUMN_AGE = "AGE"
COLUMN_GENERATION = "GENERATION"
COLUMN_MX = "MX"
COLUMN_DX = "DX"
COLUMN_EX = "EX"
COLUMN_LOG_MX = "LOG_MX"
COLUMN_CENTERED_AGE = "CENTERED_AGE"
COLUMN_SIGMA_CENTERED_AGE = "SIGMA_CENTERED_AGE"
COLUMN_ONES = "ONES"
COLUMN_ZEROS = "ZEROS"

# PREDICTION
COLUMN_MX_PRED = "MX_PRED"
COLUMN_RESIDUALS = "RESIDUALS"
COLUMN_DX_PRED = "DX_PRED"
COLUMN_RESULT = "RESULT"

# MODEL CONVERGENCE 
EPS = 1e-10
MAX_ITER = 5000

# PARAMS
PARAMS_VALUE = "VALUE"
PARAMS_INDEX = "INDEX"
PARAMS_A1 = "A1"
PARAMS_A2 = "A2"
PARAMS_DERIVATIVE = "DERIVATIVE"
PARAMS_VARIABLE = "VAR"
PARAMS_VALUE_NAME = "VALUE_NAME"

# LEE-CARTER
LC_AX = "ALPHA_X"
LC_B1X = "BETA1_X"
LC_K1T = "KAPPA1_T"

# CBD
CBD_K1T = "KAPPA1_T"
CBD_K2T = "KAPPA2_T"

# M6
M6_K1T = "KAPPA1_T"
M6_K2T = "KAPPA2_T"
M6_GTX = "GAMMA_TX"

# APC
APC_AX = "ALPHA_X"
APC_K1T = "KAPPA1_T"
APC_GTX = "GAMMA_TX"

# M7
M7_K1T = "KAPPA1_T"
M7_K2T = "KAPPA2_T"
M7_K3T = "KAPPA3_T"
M7_GTX = "GAMMA_TX"

# M8
M8_K1T = "KAPPA1_T"
M8_K2T = "KAPPA2_T"
M8_GTX = "GAMMA_TX"
M8_XC = "XC"